name: Build HUMI Signed APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      run: npm install
        
    - name: Create web build directory
      run: |
        mkdir -p dist
        echo '<!DOCTYPE html><html><head><title>HUMI</title></head><body><div id="root"></div></body></html>' > dist/index.html
        
    - name: Add Android platform
      run: npx cap add android
        
    - name: Create Android assets directory
      run: |
        mkdir -p android/app/src/main/assets
        
    - name: Sync Capacitor
      run: npx cap sync android
        
    - name: Generate upload keystore
      run: |
        keytool -genkey -v -keystore android/app/upload-keystore.jks \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -alias upload -storepass android -keypass android \
          -dname "CN=HUMI, OU=Development, O=HUMI, L=Rome, S=Lazio, C=IT"
        
    - name: Configure signing
      run: |
        cat >> android/gradle.properties << EOF
        MYAPP_UPLOAD_STORE_FILE=upload-keystore.jks
        MYAPP_UPLOAD_KEY_ALIAS=upload
        MYAPP_UPLOAD_STORE_PASSWORD=android
        MYAPP_UPLOAD_KEY_PASSWORD=android
        EOF
        
    - name: Update build.gradle for signing
      run: |
        sed -i '/android {/a\
            signingConfigs {\
                release {\
                    if (project.hasProperty("MYAPP_UPLOAD_STORE_FILE")) {\
                        storeFile file(MYAPP_UPLOAD_STORE_FILE)\
                        storePassword MYAPP_UPLOAD_STORE_PASSWORD\
                        keyAlias MYAPP_UPLOAD_KEY_ALIAS\
                        keyPassword MYAPP_UPLOAD_KEY_PASSWORD\
                    }\
                }\
            }' android/app/build.gradle
            
        sed -i '/buildTypes {/,/}/ s/debug {/debug {\
                signingConfig signingConfigs.release/' android/app/build.gradle
        
    - name: Build signed APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon
        
    - name: Upload signed APK
      uses: actions/upload-artifact@v4
      with:
        name: humi-signed-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
