name: Build HUMI App Bundle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      run: npm install
        
    - name: Create web build
      run: |
        mkdir -p dist
        echo '<!DOCTYPE html><html><head><title>HUMI</title></head><body><div id="root"></div></body></html>' > dist/index.html
        
    - name: Fix Capacitor config
      run: |
        cat > capacitor.config.ts << 'EOF'
        import type { CapacitorConfig } from '@capacitor/cli';
        
        const config: CapacitorConfig = {
          appId: 'com.humi.journal',
          appName: 'HUMI',
          webDir: 'dist',
          server: {
            androidScheme: 'https'
          }
        };
        
        export default config;
        EOF
        
    - name: Add Android platform
      run: npx cap add android
        
    - name: Manual assets copy
      run: |
        mkdir -p android/app/src/main/assets
        cp -r dist/* android/app/src/main/assets/ || echo "Assets copied"
        echo '{}' > android/app/src/main/assets/capacitor.config.json
        echo '[]' > android/app/src/main/assets/capacitor.plugins.json
        
    - name: Create upload keystore with specific settings
      run: |
        keytool -genkey -v -keystore android/app/upload-keystore.jks \
          -keyalg RSA -keysize 2048 -validity 25000 \
          -alias upload -storepass humijournal2025 -keypass humijournal2025 \
          -dname "CN=HUMI Journal, OU=HUMI Development Team, O=HUMI, L=Rome, S=Lazio, C=IT"
        
    - name: Configure signing properties
      run: |
        cat >> android/gradle.properties << EOF
        HUMI_RELEASE_STORE_FILE=upload-keystore.jks
        HUMI_RELEASE_KEY_ALIAS=upload
        HUMI_RELEASE_STORE_PASSWORD=humijournal2025
        HUMI_RELEASE_KEY_PASSWORD=humijournal2025
        EOF
        
    - name: Update build.gradle for proper signing
      run: |
        sed -i '/signingConfigs {/,/}/c\
            signingConfigs {\
                release {\
                    storeFile file("upload-keystore.jks")\
                    storePassword "humijournal2025"\
                    keyAlias "upload"\
                    keyPassword "humijournal2025"\
                }\
            }' android/app/build.gradle
        
    - name: Build signed App Bundle
      run: |
        cd android
        chmod +x gradlew
        ./gradlew clean bundleRelease --no-daemon --stacktrace
        
    - name: Verify bundle signature
      run: |
        cd android/app/build/outputs/bundle/release
        ls -la
        
    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: humi-signed-bundle
        path: android/app/build/outputs/bundle/release/app-release.aab
        if-no-files-found: error
