name: Build HUMI App Bundle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      run: npm install
        
    - name: Create web build
      run: |
        mkdir -p dist
        echo '<!DOCTYPE html><html><head><title>HUMI</title></head><body><div id="root"></div></body></html>' > dist/index.html
        
    - name: Fix Capacitor config
      run: |
        cat > capacitor.config.ts << 'EOF'
        import type { CapacitorConfig } from '@capacitor/cli';
        
        const config: CapacitorConfig = {
          appId: 'com.humi.app',
          appName: 'HUMI',
          webDir: 'dist',
          server: {
            androidScheme: 'https'
          }
        };
        
        export default config;
        EOF
        
    - name: Add Android platform
      run: npx cap add android
        
    - name: Manual assets copy
      run: |
        mkdir -p android/app/src/main/assets
        cp -r dist/* android/app/src/main/assets/ || echo "Assets copied"
        echo '{}' > android/app/src/main/assets/capacitor.config.json
        echo '[]' > android/app/src/main/assets/capacitor.plugins.json
        
    - name: Generate keystore
      run: |
        keytool -genkey -v -keystore android/app/upload-keystore.jks \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -alias upload -storepass humi2025 -keypass humi2025 \
          -dname "CN=HUMI App, OU=Mobile, O=HUMI, L=Rome, S=Lazio, C=IT"
        
    - name: Configure signing
      run: |
        cat >> android/gradle.properties << EOF
        MYAPP_UPLOAD_STORE_FILE=upload-keystore.jks
        MYAPP_UPLOAD_KEY_ALIAS=upload
        MYAPP_UPLOAD_STORE_PASSWORD=humi2025
        MYAPP_UPLOAD_KEY_PASSWORD=humi2025
        EOF
        
    - name: Add signing to build.gradle
      run: |
        sed -i '/android {/a\
            signingConfigs {\
                release {\
                    storeFile file("upload-keystore.jks")\
                    storePassword "humi2025"\
                    keyAlias "upload"\
                    keyPassword "humi2025"\
                }\
            }' android/app/build.gradle
            
        sed -i '/buildTypes {/,/}/ s/release {/release {\
                signingConfig signingConfigs.release/' android/app/build.gradle
        
    - name: Verify build.gradle
      run: |
        echo "=== Current build.gradle ==="
        cat android/app/build.gradle
        
    - name: Build App Bundle
      run: |
        cd android
        chmod +x gradlew
        ./gradlew bundleRelease --no-daemon --stacktrace
        
    - name: List output files
      run: |
        echo "=== Bundle output directory ==="
        ls -la android/app/build/outputs/bundle/release/ || echo "Release directory not found"
        echo "=== All bundle outputs ==="
        find android/app/build/outputs -name "*.aab" -o -name "*.apk" || echo "No AAB/APK files found"
        
    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: humi-app-bundle-v1-0-1
        path: android/app/build/outputs/bundle/release/*.aab
        if-no-files-found: error
