name: HUMI Android Bundle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Accept Android licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
      
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      
    - name: Build frontend only
      run: |
        export NODE_ENV=production
        npx vite build --config vite.config.ts
        
    - name: Verify build output
      run: |
        ls -la dist/public/
        echo "Build files ready for Capacitor"
        
    - name: Setup Capacitor webDir
      run: |
        mkdir -p client/dist
        cp -r dist/public/* client/dist/
        ls -la client/dist/
        
    - name: Capacitor operations
      run: |
        npx cap add android || echo "Android platform exists"
        npx cap sync android
        
    - name: Create signing keystore
      run: |
        keytool -genkey -v -keystore android/app/upload-keystore.jks \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -alias upload -storepass password -keypass password \
          -dname "CN=HUMI,
