name: Android App Bundle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Accept licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
      
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      
    - name: Build web app
      run: |
        npx vite build
        mkdir -p client/dist
        cp -r dist/public/* client/dist/
        
    - name: Capacitor sync
      run: |
        npx cap add android || echo "Platform exists"
        npx cap sync android
        
    - name: Generate keystore
      run: |
        keytool -genkey -v -keystore android/app/upload-keystore.jks \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -alias upload -storepass password -keypass password \
          -dname "CN=HUMI, OU=Development, O=HUMI, L=Milan, S=IT, C=IT"
        
    - name: Configure signing
      run: |
        cat >> android/gradle.properties << 'EOF'
        HUMI_RELEASE_STORE_FILE=upload-keystore.jks
        HUMI_RELEASE_KEY_ALIAS=upload
        HUMI_RELEASE_STORE_PASSWORD=password
        HUMI_RELEASE_KEY_PASSWORD=password
        EOF
        
    - name: Build AAB
      run: |
        cd android
        chmod +x gradlew
        ./gradlew bundleRelease
        
    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: humi-app-bundle
        path: android/app/build/outputs/bundle/release/app-release.aab
        retention-days: 30
