name: HUMI Bundle - Simple Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Accept Android licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        
    - name: Install Node dependencies
      run: npm install --force
        
    - name: Create basic web build
      run: |
        mkdir -p dist
        cat > dist/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="it">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>HUMI Journal</title>
        </head>
        <body>
          <div id="root">
            <h1>HUMI - Journal App</h1>
            <p>Versione 1.0.2</p>
          </div>
        </body>
        </html>
        EOF
        
    - name: Initialize Capacitor Android
      run: |
        npx cap add android || echo "Android platform already exists"
        
    - name: Create required assets
      run: |
        mkdir -p android/app/src/main/assets
        echo '{}' > android/app/src/main/assets/capacitor.config.json
        echo '[]' > android/app/src/main/assets/capacitor.plugins.json
        cp dist/index.html android/app/src/main/assets/ || echo "HTML copied"
        
    - name: Sync Capacitor
      run: npx cap sync android
        
    - name: Create keystore
      run: |
        mkdir -p android/app
        keytool -genkey -noprompt \
          -keystore android/app/release.jks \
          -keyalg RSA -keysize 2048 -validity 365 \
          -alias release \
          -storepass android -keypass android \
          -dname "CN=HUMI, OU=App, O=HUMI, L=Milano, ST=IT, C=IT"
        
    - name: Configure signing in Gradle
      run: |
        echo "" >> android/gradle.properties
        echo "HUMI_RELEASE_STORE_FILE=release.jks" >> android/gradle.properties
        echo "HUMI_RELEASE_KEY_ALIAS=release" >> android/gradle.properties
        echo "HUMI_RELEASE_STORE_PASSWORD=android" >> android/gradle.properties
        echo "HUMI_RELEASE_KEY_PASSWORD=android" >> android/gradle.properties
        
    - name: Fix Java compatibility
      run: |
        # Force Java 17 in build.gradle
        sed -i 's/sourceCompatibility JavaVersion.VERSION_21/sourceCompatibility JavaVersion.VERSION_17/g' android/app/build.gradle
        sed -i 's/targetCompatibility JavaVersion.VERSION_21/targetCompatibility JavaVersion.VERSION_17/g' android/app/build.gradle
        sed -i 's/jvmTarget = "21"/jvmTarget = "17"/g' android/app/build.gradle
        sed -i 's/compileSdk 35/compileSdk 34/g' android/app/build.gradle
        sed -i 's/targetSdk 35/targetSdk 34/g' android/app/build.gradle
        
        # Also check capacitor modules
        find android -name "build.gradle" -exec sed -i 's/sourceCompatibility JavaVersion.VERSION_21/sourceCompatibility JavaVersion.VERSION_17/g' {} \;
        find android -name "build.gradle" -exec sed -i 's/targetCompatibility JavaVersion.VERSION_21/targetCompatibility JavaVersion.VERSION_17/g' {} \;
        find android -name "build.gradle" -exec sed -i 's/jvmTarget = "21"/jvmTarget = "17"/g' {} \;
        
    - name: Make Gradle executable
      run: chmod +x android/gradlew
        
    - name: Build signed AAB
      run: |
        cd android
        ./gradlew clean
        ./gradlew bundleRelease --no-daemon --stacktrace
        
    - name: Find and list generated files
      run: |
        echo "=== Generated files ==="
        find android -name "*.aab" -o -name "*.apk" | head -20
        echo "=== Bundle directory ==="
        ls -la android/app/build/outputs/bundle/release/ 2>/dev/null || echo "No release bundle found"
        echo "=== APK directory ==="
        ls -la android/app/build/outputs/apk/debug/ 2>/dev/null || echo "No debug APK found"
        
    - name: Upload signed bundle
      uses: actions/upload-artifact@v4
      with:
        name: humi-signed-bundle
        path: |
          android/app/build/outputs/bundle/release/app-release.aab
          android/app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: warn
        retention-days: 30
        
    - name: Create info file
      run: |
        echo "HUMI App Bundle Build Info" > build-info.txt
        echo "Date: $(date)" >> build-info.txt
        echo "Version: 1.0.2" >> build-info.txt
        echo "Build: Release AAB for Google Play" >> build-info.txt
        
    - name: Upload build info
      uses: actions/upload-artifact@v4
      with:
        name: build-info
        path: build-info.txt
