name: Android AAB Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies and build web
      run: |
        npm ci
        npm run build
        
    - name: Setup Capacitor
      run: |
        npx cap add android
        npx cap sync android
        
    - name: Create keystore
      run: |
        mkdir -p android/app
        keytool -genkey -v -keystore android/app/upload-keystore.jks \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -alias upload -storepass password -keypass password \
          -dname "CN=HUMI, OU=Development, O=HUMI, L=Milan, S=Lombardy, C=IT"
        
    - name: Setup signing config
      run: |
        echo "HUMI_UPLOAD_STORE_FILE=upload-keystore.jks" >> android/gradle.properties
        echo "HUMI_UPLOAD_KEY_ALIAS=upload" >> android/gradle.properties
        echo "HUMI_UPLOAD_STORE_PASSWORD=password" >> android/gradle.properties
        echo "HUMI_UPLOAD_KEY_PASSWORD=password" >> android/gradle.properties
        
    - name: Build release AAB
      run: |
        cd android
        chmod +x gradlew
        ./gradlew bundleRelease
        
    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: android/app/build/outputs/bundle/release/app-release.aab
