name: Build HUMI Android App Bundle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Accept Android licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
      
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      
    - name: Create production web build
      run: |
        mkdir -p client/dist
        cat > client/dist/index.html << 'EOF'
<!DOCTYPE html>
<html lang="it">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>HUMI</title>
  <meta name="theme-color" content="#667eea">
  <style>
    body { 
      font-family: system-ui, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white; 
      margin: 0; 
      min-height: 100vh; 
      display: flex;
      align-items: center; 
      justify-content: center; 
      text-align: center;
    }
    .app { max-width: 400px; padding: 40px; }
    h1 { font-size: 3em; margin-bottom: 20px; }
    .subtitle { font-size: 1.2em; opacity: 0.9; }
  </style>
</head>
<body>
  <div class="app">
    <div style="font-size: 4em; margin-bottom: 20px;">🌱</div>
    <h1>HUMI</h1>
    <div class="subtitle">Daily Journal for Emotional Wellbeing</div>
  </div>
</body>
</html>
EOF
        echo "Web build created"
        ls -la client/dist/
        
    - name: Sync Capacitor
      run: |
        npx cap add android --quiet || true
        npx cap sync android --quiet
        echo "Capacitor sync completed"
        
    - name: Generate signing keystore
      run: |
        keytool -genkey -v -keystore android/app/upload-keystore.jks \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -alias upload -storepass password -keypass password \
          -dname "CN=HUMI, OU=Development, O=HUMI, L=Milan, S=IT, C=IT"
        echo "Keystore generated"
        
    - name: Configure signing properties
      run: |
        echo "HUMI_RELEASE_STORE_FILE=upload-keystore.jks" >> android/gradle.properties
        echo "HUMI_RELEASE_KEY_ALIAS=upload" >> android/gradle.properties
        echo "HUMI_RELEASE_STORE_PASSWORD=password" >> android/gradle.properties
        echo "HUMI_RELEASE_KEY_PASSWORD=password" >> android/gradle.properties
        echo "Signing properties configured"
        
    - name: Build Android App Bundle
      run: |
        cd android
        chmod +x gradlew
        ./gradlew clean
        ./gradlew bundleRelease --no-daemon --stacktrace
        echo "Build completed"
        
    - name: Verify and upload AAB
      run: |
        find android -name "*.aab" -type f
        AAB_FILE=$(find android -name "*.aab" -type f | head -1)
        if [ -n "$AAB_FILE" ]; then
          echo "AAB found: $AAB_FILE"
          ls -lh "$AAB_FILE"
          mkdir -p artifacts
          cp "$AAB_FILE" artifacts/humi-release.aab
        else
          echo "No AAB file found"
          exit 1
        fi
        
    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: humi-android-bundle
        path: artifacts/humi-release.aab
        retention-days: 30
